### ISSUE TITLE
type-safe lens

### ISSUE THREAD

**Issue by miguel-negrao** [expipiplus1/vector-sized#106]
Hi

Wouldn't it make sense to add a type-safe lens ? Using type applications it becomes quite compact.

```Haskell
ix' :: forall m (n :: Nat) a (f :: * -> *).
  (Functor f, KnownNat m, KnownNat n, m+1 <= n) =>
  (a -> f a) -> Vec.Vector n a -> f (Vec.Vector n a)
ix' = ix $ natToFinite (Proxy::Proxy m)
```

This can be then be used like so:

```
ix' @7
```

**Comment by expipiplus1** [comment]
Sure if you'd find it useful it sounds like a good addition, feel free to open a PR.

Seems to me to be quite close to the Fairbairn threshold though.
