### ISSUE TITLE
Should the ordering of additions in types be more consistent, for the sake of proofs?

### ISSUE THREAD

**Issue by mstksg** [expipiplus1/vector-sized#14]
Addition is commutative, so semantically it shouldn't make a difference, but right now the ordering of additions in the library is a bit inconsistent with respect to the underlying structure of the vectors.

For example, we have `(++)`, `splitAt`, `drop`, `snoc`, and `init`, which treat `Vector (n + m) a` as a `Vector n a` proceeded by a `Vector m a`:

~~~
(++) :: Vector n a -> Vector m a -> Vector (n + m) a
splitAt :: Vector (n + m) a -> (Vector n a, Vector m a)
drop :: Vector (n + m) a -> Vector m a
snoc :: Vector n a -> a -> Vector (n + 1) a
init :: Vector (n + 1) a -> Vector n a
~~~

But we also have `cons`, `head`, `tail`, `take`, which treat a `Vector (n + m) a` as a `Vector m a` followed by a `Vector n a`:

~~~
cons :: a -> Vector n a -> Vector (n + 1) a
head :: Vector (n + 1) a -> a
tail :: Vector (n + 1) a -> Vector n a
take :: Vector (n + m) a -> Vector m a
~~~

For concrete `Nat`s and in monomorphic cases, both orderings are equivalent, of course, and there shouldn't be a difference at runtime between a `Vector (n + m) a` and a `Vector (m + n) a`.  However, in making proofs based on concatenating, taking, dropping, consing, etc. vectors in the polymorphic case, treating the different sides of the `+` consistently makes it a lot simpler.  If I have a `n + m + p :: Nat`, and I want to split things into three parts right now, I'd have to work with how `take` and `drop` are inconsistent (`take` expects the initial part of the vector to be on the right hand side of `+`, and `drop` expects the initial part to be on the left hand side of `+`), and manually commute `m` and `p` and `n` back and forth to get GHC to be happy.  If it was all consistent, then it'd be as simple as a `take` and a `drop`.

Is there a specific reason/logic behind the current ordering of additions now?

**Comment by expipiplus1** [comment]
I think it'd make a lot of sense to reorder the additions in `cons`, `head`, `tail` and `take`!

I've never actually bumped into ay problems before due to this though, perhaps because I'm quite fond of https://hackage.haskell.org/package/ghc-typelits-natnormalise and https://hackage.haskell.org/package/ghc-typelits-extra

**Comment by expipiplus1** [comment]
@mstksg I've made an attempt at this in #20. I'd really appreciate it if you could give it a thumbs up and merge it if it looks good!

**Comment by mstksg** [comment]
I'll look deeper later today when I get the chance.

For what it's worth, though, I took your suggestion and began using `ghc-typelits-natnormalise` and the actual practical issues I was facing went away for the most part :)  It'd still be nice to have the fix, however, for the sake of consistency (if anything).
