### ISSUE TITLE
Provide lenses

### ISSUE THREAD

**Issue by k0ral** [expipiplus1/vector-sized#22]
Would you accept a pull-request to implement lenses on `Vector n a` (without adding any new dependency) ? I'm thinking about the following ones:
- `ix`-like lens: `KnownNat n => Finite n -> Lens (Vector n a) a`
- `_head`-like lens:  `KnownNat n => Lens (Vector (n+1) a) a`
- `_last`-like lens: `KnownNat n => Lens (Vector (n+1) a) a`

If so, how would you suggest to name them, to avoid confusion with the existing `ix`, `_head` and `_last` ?

**Comment by mstksg** [comment]
Would be in favor of an `ix` lens.   Calling it `ix` might be fine, since I'd think that most people import these modules qualified anyway.

**Comment by expipiplus1** [comment]
For, `_head` the type signature should probably be `KnownNat n => Lens (Vector (1+n) a) a`.

@k0ral Are you planning a PR for `_head` and `_last`?

**Comment by k0ral** [comment]
@expipiplus1 I've updated #23 with `_head` and `_last`.

Is there a difference between `Vector (1+n) a` and `Vector (n+1) a` ?

**Comment by mstksg** [comment]
@k0ral see #14 for some discussion.  Without the help of typechecker plugins, ghc can't unify `forall n. KnownNat n => n + 1` and `forall n. KnownNat n => 1 + n`.  It can unify them for specific n's, but not in situations polymorphic over all n.

**Comment by k0ral** [comment]
My implementation of `_head` relies on the existing `head :: Vector (n+1) a -> a` so the signature of the latter must be updated as well if I am to use `Vector (1+n) a`. Should I proceed ?

**Comment by mstksg** [comment]
@k0ral See #20
