### ISSUE TITLE
Finite-based imap variant

### ISSUE THREAD

**Issue by conal** [expipiplus1/vector-sized#26]
I need a variant of `imap` that uses `Finite` in place of `Int`. Here's my clumsy implementation:

``` haskell
imap' :: KnownNat n => (Finite n -> a -> b) -> Vector n a -> Vector n b
imap' f = V.imap (f . fromMaybe err . packFinite . fromIntegral)
 where
   err = error "imap': out of bounds"
{-# INLINE imap' #-}
```

Better would be to eliminate the error, since I it can't really occur. I don't know how to avoid it.

**Comment by conal** [comment]
Of course, using whatever name you deem best.

**Comment by expipiplus1** [comment]
Looks very useful! I've defined something similar in the past, I'll see if I can find that tomorrow. 

I'm sure [finites](https://hackage.haskell.org/package/finite-typelits-0.1.2.0/docs/Data-Finite.html#v:finites) will be useful.

**Comment by conal** [comment]
Thanks.

> I'm sure [finites](https://hackage.haskell.org/package/finite-typelits-0.1.2.0/docs/Data-Finite.html#v:finites) will be useful.

Or (together with `liftA2`) a variant of `finites` that yields a `Vector n (Finite n)`, which would probably be useful as well.

**Comment by mstksg** [comment]
This is actually already a part of #17 :)  We use the unsafe Finite constructor safely to implement it.

**Comment by conal** [comment]
I just noticed `finite`, allowing a simpler definition:

``` haskell
imap' :: KnownNat n => (Finite n -> a -> b) -> Vector n a -> Vector n b
imap' f = V.imap (f . finite . fromIntegral)
{-# INLINE imap' #-}
```

On the other hand, @mstksg's version in PR #17 is likely preferable.

**Comment by expipiplus1** [comment]
#17 merged!

**Comment by conal** [comment]
Thanks, @mstksg and @expipiplus1!
