### ISSUE TITLE
Plans for consolidating/pushing to hackage, for ghc 8.4/stackage nightlies?

### ISSUE THREAD

**Issue by mstksg** [expipiplus1/vector-sized#34]
Hi!  GHC 8.4 is released, so the current version of this package on stackage no longer builds; both #28 and #33 are able to allow for a quick fix with minimal changes to the library.  If you want, I can consolidate one of those two, update the changelogs/versions, and push it to hackage (and stackage) just a quick patch? :)

**Comment by expipiplus1** [comment]
I've just merged most of the PRs into a larger change, once that passes travis we can merge all the recent features in one go. Thanks for the prodding!
