### ISSUE TITLE
Some thoughts/reservations about v1.0.1.0's dependencies

### ISSUE THREAD

**Issue by mstksg** [expipiplus1/vector-sized#39]
Just some thoughts :)  Just wanted to note that the most recent version v1.0.1.0 came with a somewhat significant explosion in transitive dependencies.

I understand the reason why these were added; orphan instances are an ugly thing and there isn't really a satisfying way to use vector with Distributive save for distributive the package pulling it in, or having ugly orphan instances strewn about.

However, I had been using/thinking about this library as a bare minimal thin wrapper over the *vector* package; this might be some platonic ideal that is broken with the new dependencies.

There isn't really an ideal situation here (except for *distributive* depending on this package maybe), so this isn't really a call to action one way or the other.  Just leaving this here as a note in case you had any thoughts!

# Version 1.0.0.0 Dependencies
![v1.0.0.0 deps](https://i.imgur.com/Qm97BAB.png)

# Version 1.0.1.0 Dependencies
![v1.0.1.0 deps](https://i.imgur.com/XmMN3eU.png)

**Comment by expipiplus1** [comment]
Good thoughts. I wish it was possible to publish these kind of instances in
a cost free way (i.e. Only include then if the project already uses
distrobutive)

I think raising an issue against the distributive package would be a good
course of action.

**Comment by mstksg** [comment]
Yeah :'(  A lack of that sort of feature is a cause of great pain in the Haskell ecosystem at the moment.

Small thing I just realized, if we remove the `Representable` instance and only have `Distributive`, the resulting deps aren't too bad:

![no-rep](https://i.imgur.com/d2E14bN.png)

This is actually pretty much no extra cost, because `Cabal` is already a dependency of GHC and it's not possible to really use Haskell without having `Cabal` already installed in some form or another.

Still would require orphan instances of Representable for those who need it, unfortunately.  However, since its functionality is already given by `generate` and `index`, you'd probably only need it if you want to write Representable-polymorphic functions.  But at this point it's already there and people could be relying on it, so anything involving it would be a pretty bad breaking API change, heh.

**Comment by expipiplus1** [comment]
@mstksg I've raised an issue here: https://github.com/ekmett/distributive/issues/46
