### ISSUE TITLE
redundant and missing runtime bounds check

### ISSUE THREAD

**Issue by kuribas** [expipiplus1/vector-sized#49]
index uses V.index, which does a runtime bounds check.  However this index is proven to be inside the bounds, so it should use V.unsafeIndex, which doesn't include a bounds check.  On the other hand, unsafeIndex doesn't do a bounds check, so it will crash with a segfault.  These functions should be switched for correct behaviour.  Unless this is the intended behaviour for unsafeIndex, in which case there should be a function which doesn't segfault when out of bounds.

**Comment by kuribas** [comment]
Never mind, I looked at the wrong module!

**Comment by expipiplus1** [comment]
Glad it's worked out! Thanks!
