### ISSUE TITLE
Upload 1.0.4.1 to Hackage

### ISSUE THREAD

**Issue by DarinM223** [expipiplus1/vector-sized#52]
So packages that depend on vector-sized can build on GHC 8.6

**Comment by mstksg** [comment]
See discussion for #48, which mentions an issue in haskell/hackage-server#788 that is still unresolved.

**Comment by DarinM223** [comment]
In hindsight, it might've been better to write the NoStarIsType extensions manually like https://github.com/vincenthz/hs-memory/pull/68/files instead of using default-extensions, since this was able to be uploaded right away.

**Comment by mstksg** [comment]
I'm not sure if it's better on hindsight, since either way in the end we get the same result :)  The cost is a delay of a couple of weeks at most, and the benefit is long-term cleaner code base and avoidance of CPP.

**Comment by mstksg** [comment]
Just checking in about a week after the lack of a timeline on the hackage infrastructure update; if there continues to be no response from hackage maintainers then it might be worth looking into CPP based options?

**Comment by expipiplus1** [comment]
I've got no problem with a CPP based solution. Worst case we can switch back once hackage is up to date.

**Comment by turion** [comment]
Any activity? Do you want a PR with a CPP solution?

**Comment by mstksg** [comment]
#55 is an open PR moving things to CPP that should upload.  Perhaps if @expipiplus1 approves I can merge it in and push to hackage later tonight.  However, it should be noted that hackage is also apparently to be updated this upcoming weekend as well (according to https://github.com/haskell/hackage-server/issues/788), so the issue might be moot by then.

**Comment by expipiplus1** [comment]
I'll take a look tonight! Thanks for the reminder.

@justinle, I think you're also able to approve PRs for this repo.

Joe

**Comment by expipiplus1** [comment]
1.1.0.0 is on hackage now. Thanks!

**Comment by mstksg** [comment]
(Quick note that 1.1.0.0 does not currently build on ghc 8.6, pending #59)
