### ISSUE TITLE
Are you OK with any of the following?

### ISSUE THREAD

**Issue by kozross** [expipiplus1/vector-sized#62]
There's a bunch of stuff I'd like to commit, but I don't know if this is something you'd be in favour of, so I figured I'd list them here, and if you're OK with them, then I can write them and commit.

**Use of [HLint][1]**

On a casual glance, HLint found quite a few things which are obviously issues (redundant ``LANGUAGE`` pragmata, unnecessary bracketing, etc), but these don't affect compilation. While I'm a big fan of linters as a sanity check, you might not be. Additionally, this can't be done blindly (such as the warning about a non-canonical ``mappend``). I'd be quite willing to go through and make these changes systematically, but only if this is something you're good with.

On a related note: would you be OK with some kind of standard for code layout? I'm fond of ``hindent`` myself (which I haven't been using on my contributions as it's rather opinionated), but this is definitely something that the primary maintainer should have a call over. Again, the code's quite big, so it could help.

**Generalize ``concatMap`` to allow 'inner' and 'outer' vector types to vary**

Relevant links are [my work in ``vector-sized-extra``][2] and [the Twitter discussion of same][3]. In short, I'd like to generalize the signature of ``concatMap`` to be

```haskell
concatMap :: (VG.Vector v a, VG.Vector v' b) => (a -> Vector v' m a) -> Vector v n a -> Vector v' (n * m) a
```

This is primarily to unify my own version of ``concat`` with ``concatMap``, to enable exactly the [example given here][4]. 

**Add ``Hashable`` instances**

This is something that's done by ``vector-instances``, but as that package is a large collection of orphans, it's not entirely problem-free. Given how 'obvious' these instances are, I can't think of any good reason not to include them, especially given that ``hashable`` is _already_ a transitive dependency (via ``semigroups`` via ``vector``, although there could be paths in the dependency graph leading to ``hashable``). Furthermore, given that you provide ``Generic`` instances already, this could be done with a single line.

[1]: http://hackage.haskell.org/package/hlint
[2]: https://notabug.org/koz.ross/vector-sized-extra/src/master/src/Data/Vector/Sized/Extra.hs#L25
[3]: https://twitter.com/KozRoss/status/1060278691198947328
[4]: https://twitter.com/basile_henry/status/1060811962756591616

**Comment by kozross** [comment]
@mstksg: Your opinion(s) would also be great!

**Comment by expipiplus1** [comment]
I'm a big fan of HLint, please submit these changes!

I really like Brittany for code formatting personally. Either that or hindent would be a welcome change though.

Generalizing concatmap seems reasonable too.

Hashable's good too.

Thanks!

**Comment by kozross** [comment]
This may be delayed somewhat, due to issues with [brittany breaking with ``cabal new-install``][1] and [hindent breaking on CPP][2].

[1]: https://github.com/lspitzner/brittany/issues/200
[2]: https://github.com/commercialhaskell/hindent/issues/525
