### ISSUE TITLE
Put vector-sized back on stackage

### ISSUE THREAD

**Issue by turion** [expipiplus1/vector-sized#63]
It seems that still if `vector-sized` compiles with GHC 8.6, it couldn't be reenabled on stackage because its dependency `finite-typelits` is on stackage (https://github.com/mniip/finite-typelits/issues/14). What could we do about that? Is stackage integration important for `vector-sized`?

**Comment by expipiplus1** [comment]
It's not important to me, but @mstksg might be interested.

**Comment by mstksg** [comment]
Hi @turion,

Projects on stackage are not required to have all their dependencies on stackage.  The only requirement is that things should build with a version consistent with all other packages on the snapshot.  vector-sized should be good for stackage even if finite-typelits is not on stackage, provided the latest version of finite-typelits builds on ghc 8.6.2.

**Comment by kozross** [comment]
We need to have a release integrating the fixes in #59, unless I missed that boat, as otherwise, ``vector-sized`` will fail to build on 8.6.

**Comment by mstksg** [comment]
@kozross #59 was actually pulled into the recent v1.1.1.0 release, and things do build now

**Comment by mstksg** [comment]
Will begin process of filing to put vector-sized back on stackage some time later today (PST), probably all together with a batch of other packages I am currently maintaining downstream of vector-sized after I patch and hackage-push them.

**Comment by turion** [comment]
@mstksg Ah, I didn't know the dependencies don't have to be there! (I assumed they had to be because otherwise `stack init --resolver nightly` would fail). Now `finite-typelits` will be there as well (https://github.com/commercialhaskell/stackage/pull/4136) and we can even remove the `extra-deps`. Great :)
