### ISSUE TITLE
index' type should have a +1?

### ISSUE THREAD

**Issue by dlthomas** [expipiplus1/vector-sized#8]
I believe `index' :: forall n m a. (KnownNat n, KnownNat m) => Vector (n + m) a -> Proxy n -> a` should be `index' :: forall n m a. (KnownNat n, KnownNat m) => Vector (n + m + 1) a -> Proxy n -> a`.

**Comment by expipiplus1** [comment]
Good spot! Thanks!

Fixed and released as 0.4.0.0
