### ISSUE TITLE
Type family equation violates the family's injectivity annotation

### ISSUE THREAD

**Issue by kozross** [expipiplus1/vector-sized#90]
I still get this issue when compiling on GHC 8.10:

```
src/Data/Vector/Generic/Sized.hs:291:15: error:
    Type family equation violates the family's injectivity annotation.
    Type variable ‘v’ cannot be inferred from the right-hand side.
    Using UndecidableInstances might help
    In the type family equation:
      VG.Mutable (Vector v n) = MVector (VG.Mutable v) n
        -- Defined at src/Data/Vector/Generic/Sized.hs:291:15
    |
291 | type instance VG.Mutable (Vector v n) = MVector (VG.Mutable v) n
    |               ^^^^^^^^^^
```

What's weird is that I can only reproduce this in the context of trying to build [``finitary``][1]. If I try to build ``vector-sized`` on its own, this doesn't come up. @mstksg @expipiplus1 - any idea what this might be caused by?

[1]: https://notabug.org/koz.ross/finitary

**Comment by sheaf** [comment]
It's due to a change in GHC 8.10. As the error message says, adding the `UndecidableInstances` pragma fixes the issue. Fixed in #87.

**Comment by kozross** [comment]
@sheaf That thing up there I pasted came from an attempt to compile ``finitary`` with GHC 8.10. Clearly I'm missing _something_. Did we cut a new release with this fix?

PS. Thanks for the praise!

**Comment by sheaf** [comment]
The version on hackage does not have the fix.

**Comment by kozross** [comment]
@expipiplus1 Cut a new release perhaps?

**Comment by expipiplus1** [comment]
Thanks for the reminder. Once https://github.com/expipiplus1/vector-sized/pull/91 passes CI I'll release.

**Comment by expipiplus1** [comment]
Released on hackage: https://hackage.haskell.org/package/vector-sized-1.4.1.0
