### ISSUE TITLE
Newest Stack LTS

### ISSUE THREAD

**Issue by baskaransri** [expipiplus1/vector-sized#94]
Hi!

I'm really enjoying the library. I'm wondering if you could put a version out for the current Stack LTS?

I find that removing all the extra deps ( replacing with []) and using lts-15.14 builds on my machine. Are there any other tests I should run?

**Comment by kozross** [comment]
We don't control what gets added to LTSes. The only thing we can do is the stuff required to add us to a nightly, which we have done. This should be addressed to whoever maintains Stackage, rather than us.

**Comment by kozross** [comment]
Also, 15.14 is already out of date. The latest LTS for 8.8.3 is 16.0.

**Comment by Bodigrim** [comment]
`vector-sized-1.4.1.0` is available from LTS 16.*, so I guess this can be closed.
