### ISSUE TITLE
zipVectorUnsafe

### ISSUE THREAD

**Issue by Bodigrim** [expipiplus1/vector-sized#95]
I [recently needed](https://github.com/Bodigrim/arithmoi/pull/208/files#diff-7e4c4fb9b7f0c60e49916fd572bf7810R51) a generalization of `withVectorUnsafe`, operating on two vectors:

```haskell
zipVectorUnsafe :: (u a -> v b -> w c) -> Vector u n a -> Vector v n b -> Vector w n c 
```

Would a PR adding such function be accepted?

**Comment by Bodigrim** [comment]
@kozross @expipiplus1 ping

**Comment by kozross** [comment]
I think that should be OK? At least I can't see a reason why not.

**Comment by expipiplus1** [comment]
Fine with me, if possible please make sure to add it to all the different
flavours. Thanks!
