### ISSUE TITLE
Data.Vector.Primitive.Sized

### ISSUE THREAD

**Issue by Bodigrim** [expipiplus1/vector-sized#96]
Is there any particular reason why `Data.Vector.Primitive.Sized` is absent? Seems to be the only missing flavour to be on par with `vector`.

**Comment by kozross** [comment]
Nobody's asked for it, mostly. It'd be easy to do (basically, take the `Storable` or `Unboxed` version, and find-replace a whole bunch).

**Comment by expipiplus1** [comment]
> Nobody's asked for it, mostly. It'd be easy to do (basically, take the `Storable` or `Unboxed` version, and find-replace a whole bunch).

I wonder if it's worth automating this, either with some preprocessor or with backpack maybe?

**Comment by kozross** [comment]
Backpack would be awesome, but unfortunately, Stack doesn't support it last I checked.

**Comment by Bodigrim** [comment]
Stack does not support Backpack, and judging from https://github.com/commercialhaskell/stack/issues/2540 this is not going to change soon.

**Comment by expipiplus1** [comment]
> Stack does not support Backpack, and judging from [commercialhaskell/stack#2540](https://github.com/commercialhaskell/stack/issues/2540) this is not going to change soon.

Yeah, what a shame, seems to be some kind of chicken-egg problem
